/* Enemy_Llama physical presets. GPL-3.0-or-later. */
#ifndef LUX_ENEMY_LLAMA_PROFILES_H
#define LUX_ENEMY_LLAMA_PROFILES_H
#include <cstddef>

// Numeric/settings data extracted from the user-provided entity files.
// See amnesia/doc/Enemy_Llama.md for source paths and SHA-256 provenance.
// The loader applies these only when a variable is absent from the .ent file.
struct cLuxLlamaProfileVariable { const char* msName; const char* msValue; };
struct cLuxLlamaProfile
{
    const char* msName;
    const cLuxLlamaProfileVariable* mpVariables;
    std::size_t mlVariableCount;
};

static const cLuxLlamaProfileVariable kLuxLlamaProfileGrunt[] =
{
    { "Health", "100" },
    { "Toughness", "0" },
    { "MaxRegenHealth", "100" },
    { "RegenHealthSpeed", "5" },
    { "Body_Size", "1.2 1.85 1.2" },
    { "Body_Mass", "50" },
    { "Body_AccurateClimbing", "true" },
    { "Body_MaxNoSlideSlopeAngle", "45" },
    { "Body_MaxPushMass", "40" },
    { "Body_PushForce", "200" },
    { "Body_CharacterMaxPushMass", "20" },
    { "Body_CharacterPushForce", "100" },
    { "Body_MaxStepSize", "0.5" },
    { "Body_StepClimbSpeed", "6.0" },
    { "Body_OffsetRot", "0 180 0" },
    { "Body_OffsetTrans", "0 -0.02 0" },
    { "Walk_ForwardSpeed", "1.3" },
    { "Walk_BackwardSpeed", "0.4" },
    { "Walk_ForwardAcc", "2.0" },
    { "Walk_ForwardDeacc", "18.0" },
    { "Run_ForwardSpeed", "5.1" },
    { "Run_BackwardSpeed", "2.0" },
    { "Run_ForwardAcc", "4.0" },
    { "Run_ForwardDeacc", "8.0" },
    { "TurnSpeedMul", "6" },
    { "TurnMaxSpeed", "12" },
    { "TurnMinBreakAngle", "10" },
    { "TurnBreakMul", "2" },
    { "MoveSpeedAnimMul", "1.2" },
    { "StoppedToWalkSpeed", "0.15" },
    { "WalkToStoppedSpeed", "0.1" },
    { "WalkToRunSpeed", "3.2" },
    { "RunToWalkSpeed", "2.8" },
    { "WaterStepSpeedWalk", "3.0" },
    { "WaterStepSpeedRun", "5.0" },
    { "WaterStepSpeedMisc", "3.0" },
    { "HitPS_Sword", "hit/blood.ps" },
    { "HitSound_Sword", "grunt/hit_generic" },
    { "HitPS_Club", "hit/blood.ps" },
    { "HitSound_Club", "grunt/hit_generic" },
    { "HitPS_Bullet", "hit/blood.ps" },
    { "HitSound_Bullet", "grunt/hit_generic" },
    { "HitPS_Dud", "" },
    { "HitSound_Dud", "" },
    { "NormalAttackDistance", "1.9" },
    { "NormalDamageSize", "1 1.6 1.75" },
    { "NormalDamageOffset", "0 0 1.2" },
    { "NormalAttackHitSound", "grunt/attack_claw_hit" },
    { "NormalAttackDamage", "30 60" },
    { "NormalAttackForce", "30 5" },
    { "NormalAttackStrength", "1" },
    { "NormalDamageType", "Claws" },
    { "BreakDoorAttackDamage", "26 26" },
    { "BreakDoorAttackForce", "30 5" },
    { "BreakDoorAttackStrength", "6" },
    { "BreakDoorAttackHitSound", "grunt/attack_claw_hit" },
    { "BreakDoorDamageType", "BloodSplat" },
    { "LlamaIdleAnimation", "Idle" },
    { "LlamaWalkAnimation", "Walk" },
    { "LlamaRunAnimation", "Run" },
    { "LlamaBackwardAnimation", "" },
    { "LlamaDeathAnimation", "" },
};

static const cLuxLlamaProfileVariable kLuxLlamaProfileBrute[] =
{
    { "Health", "100" },
    { "Toughness", "0" },
    { "MaxRegenHealth", "100" },
    { "RegenHealthSpeed", "5" },
    { "Body_Size", "1.5 1.85 1.5" },
    { "Body_Mass", "50" },
    { "Body_AccurateClimbing", "true" },
    { "Body_MaxNoSlideSlopeAngle", "45" },
    { "Body_MaxPushMass", "40" },
    { "Body_PushForce", "200" },
    { "Body_CharacterMaxPushMass", "20" },
    { "Body_CharacterPushForce", "100" },
    { "Body_MaxStepSize", "0.5" },
    { "Body_StepClimbSpeed", "6.0" },
    { "Body_OffsetRot", "0 180 0" },
    { "Body_OffsetTrans", "0 0 0" },
    { "Walk_ForwardSpeed", "1.3" },
    { "Walk_BackwardSpeed", "0.4" },
    { "Walk_ForwardAcc", "2.0" },
    { "Walk_ForwardDeacc", "18.0" },
    { "Run_ForwardSpeed", "5.1" },
    { "Run_BackwardSpeed", "2.0" },
    { "Run_ForwardAcc", "4.0" },
    { "Run_ForwardDeacc", "8.0" },
    { "TurnSpeedMul", "6" },
    { "TurnMaxSpeed", "10" },
    { "TurnMinBreakAngle", "10" },
    { "TurnBreakMul", "2" },
    { "MoveSpeedAnimMul", "1.2" },
    { "StoppedToWalkSpeed", "0.15" },
    { "WalkToStoppedSpeed", "0.1" },
    { "WalkToRunSpeed", "2.3" },
    { "RunToWalkSpeed", "2.1" },
    { "WaterStepSpeedWalk", "3.0" },
    { "WaterStepSpeedRun", "5.0" },
    { "WaterStepSpeedMisc", "3.0" },
    { "HitPS_Sword", "hit/blood.ps" },
    { "HitSound_Sword", "brute/hit_generic" },
    { "HitPS_Club", "hit/blood.ps" },
    { "HitSound_Club", "brute/hit_generic" },
    { "HitPS_Bullet", "hit/blood.ps" },
    { "HitSound_Bullet", "brute/hit_generic" },
    { "HitPS_Dud", "" },
    { "HitSound_Dud", "" },
    { "NormalAttackDistance", "1.9" },
    { "NormalDamageSize", "1 1.7 1.8" },
    { "NormalDamageOffset", "0 0 1.3" },
    { "NormalAttackHitSound", "brute/attack_claw_hit" },
    { "NormalAttackDamage", "50 120" },
    { "NormalAttackForce", "30 5" },
    { "NormalAttackStrength", "1" },
    { "NormalDamageType", "Slash" },
    { "BreakDoorAttackDamage", "50 56" },
    { "BreakDoorAttackForce", "30 5" },
    { "BreakDoorAttackStrength", "3" },
    { "BreakDoorAttackHitSound", "brute/attack_claw_hit" },
    { "BreakDoorDamageType", "BloodSplat" },
    { "LlamaIdleAnimation", "Idle" },
    { "LlamaWalkAnimation", "Walk" },
    { "LlamaRunAnimation", "Run" },
    { "LlamaBackwardAnimation", "" },
    { "LlamaDeathAnimation", "" },
};

static const cLuxLlamaProfileVariable kLuxLlamaProfileSuitor[] =
{
    { "Health", "100" },
    { "Toughness", "0" },
    { "MaxRegenHealth", "100" },
    { "RegenHealthSpeed", "5" },
    { "Body_Size", "1.5 1.85 1.5" },
    { "Body_Mass", "50" },
    { "Body_AccurateClimbing", "true" },
    { "Body_MaxNoSlideSlopeAngle", "45" },
    { "Body_MaxPushMass", "40" },
    { "Body_PushForce", "200" },
    { "Body_CharacterMaxPushMass", "20" },
    { "Body_CharacterPushForce", "100" },
    { "Body_MaxStepSize", "0.5" },
    { "Body_StepClimbSpeed", "6.0" },
    { "Body_OffsetRot", "0 180 0" },
    { "Body_OffsetTrans", "0 0 0" },
    { "Walk_ForwardSpeed", "1.3" },
    { "Walk_BackwardSpeed", "0.4" },
    { "Walk_ForwardAcc", "2.0" },
    { "Walk_ForwardDeacc", "18.0" },
    { "Run_ForwardSpeed", "5.1" },
    { "Run_BackwardSpeed", "2.0" },
    { "Run_ForwardAcc", "4.0" },
    { "Run_ForwardDeacc", "8.0" },
    { "TurnSpeedMul", "6" },
    { "TurnMaxSpeed", "10" },
    { "TurnMinBreakAngle", "10" },
    { "TurnBreakMul", "2" },
    { "MoveSpeedAnimMul", "1.2" },
    { "StoppedToWalkSpeed", "0.15" },
    { "WalkToStoppedSpeed", "0.1" },
    { "WalkToRunSpeed", "2.3" },
    { "RunToWalkSpeed", "2.1" },
    { "WaterStepSpeedWalk", "3.0" },
    { "WaterStepSpeedRun", "5.0" },
    { "WaterStepSpeedMisc", "3.0" },
    { "HitPS_Sword", "hit/blood.ps" },
    { "HitSound_Sword", "suitor/hit_generic" },
    { "HitPS_Club", "hit/blood.ps" },
    { "HitSound_Club", "suitor/hit_generic" },
    { "HitPS_Bullet", "hit/blood.ps" },
    { "HitSound_Bullet", "suitor/hit_generic" },
    { "HitPS_Dud", "" },
    { "HitSound_Dud", "" },
    { "NormalAttackDistance", "1.9" },
    { "NormalDamageSize", "1 1.7 1.8" },
    { "NormalDamageOffset", "0 0 1.3" },
    { "NormalAttackHitSound", "suitor/attack_claw_hit" },
    { "NormalAttackDamage", "50 120" },
    { "NormalAttackForce", "30 5" },
    { "NormalAttackStrength", "1" },
    { "NormalDamageType", "Slash" },
    { "BreakDoorAttackDamage", "50 56" },
    { "BreakDoorAttackForce", "30 5" },
    { "BreakDoorAttackStrength", "3" },
    { "BreakDoorAttackHitSound", "suitor/attack_claw_hit" },
    { "BreakDoorDamageType", "BloodSplat" },
    { "LlamaIdleAnimation", "Idle" },
    { "LlamaWalkAnimation", "Walk" },
    { "LlamaRunAnimation", "Run" },
    { "LlamaBackwardAnimation", "" },
    { "LlamaDeathAnimation", "" },
};

static const cLuxLlamaProfileVariable kLuxLlamaProfileManPig[] =
{
    { "Health", "100" },
    { "Toughness", "0" },
    { "MaxRegenHealth", "100" },
    { "RegenHealthSpeed", "5" },
    { "Body_Size", "1.2 1.85 1.2" },
    { "Body_Mass", "50" },
    { "Body_AccurateClimbing", "true" },
    { "Body_MaxNoSlideSlopeAngle", "45" },
    { "Body_MaxPushMass", "40" },
    { "Body_PushForce", "200" },
    { "Body_CharacterMaxPushMass", "20" },
    { "Body_CharacterPushForce", "100" },
    { "Body_MaxStepSize", "0.5" },
    { "Body_StepClimbSpeed", "6.0" },
    { "Body_OffsetRot", "0 180 0" },
    { "Body_OffsetTrans", "0 -0.02 0" },
    { "Walk_ForwardSpeed", "1.3" },
    { "Walk_BackwardSpeed", "0.4" },
    { "Walk_ForwardAcc", "2.0" },
    { "Walk_ForwardDeacc", "18.0" },
    { "Run_ForwardSpeed", "5.1" },
    { "Run_BackwardSpeed", "2.0" },
    { "Run_ForwardAcc", "4.0" },
    { "Run_ForwardDeacc", "8.0" },
    { "TurnSpeedMul", "6" },
    { "TurnMaxSpeed", "12" },
    { "TurnMinBreakAngle", "10" },
    { "TurnBreakMul", "2" },
    { "MoveSpeedAnimMul", "1.2" },
    { "StoppedToWalkSpeed", "0.15" },
    { "WalkToStoppedSpeed", "0.1" },
    { "WalkToRunSpeed", "3.2" },
    { "RunToWalkSpeed", "2.8" },
    { "WaterStepSpeedWalk", "3.0" },
    { "WaterStepSpeedRun", "5.0" },
    { "WaterStepSpeedMisc", "3.0" },
    { "HitPS_Sword", "hit/blood.ps" },
    { "HitSound_Sword", "grunt/hit_generic" },
    { "HitPS_Club", "hit/blood.ps" },
    { "HitSound_Club", "grunt/hit_generic" },
    { "HitPS_Bullet", "hit/blood.ps" },
    { "HitSound_Bullet", "grunt/hit_generic" },
    { "HitPS_Dud", "" },
    { "HitSound_Dud", "" },
    { "NormalDamageSize", "1 1.6 1.75" },
    { "NormalDamageOffset", "0 0 1.2" },
    { "NormalAttackDistance", "1.9" },
    { "NormalAttackHitSound", "grunt/attack_claw_hit" },
    { "NormalAttackDamage", "30 60" },
    { "NormalAttackForce", "30 5" },
    { "NormalAttackStrength", "1" },
    { "NormalDamageType", "Claws" },
    { "BreakDoorAttackDamage", "26 26" },
    { "BreakDoorAttackForce", "30 5" },
    { "BreakDoorAttackStrength", "6" },
    { "BreakDoorAttackHitSound", "grunt/attack_claw_hit" },
    { "BreakDoorDamageType", "BloodSplat" },
    { "LlamaIdleAnimation", "IdleExtra1" },
    { "LlamaWalkAnimation", "" },
    { "LlamaRunAnimation", "" },
    { "LlamaBackwardAnimation", "" },
    { "LlamaDeathAnimation", "" },
};

static const cLuxLlamaProfile kLuxLlamaProfiles[] =
{
    { "Grunt", kLuxLlamaProfileGrunt, sizeof(kLuxLlamaProfileGrunt) / sizeof(kLuxLlamaProfileGrunt[0]) },
    { "Brute", kLuxLlamaProfileBrute, sizeof(kLuxLlamaProfileBrute) / sizeof(kLuxLlamaProfileBrute[0]) },
    { "Suitor", kLuxLlamaProfileSuitor, sizeof(kLuxLlamaProfileSuitor) / sizeof(kLuxLlamaProfileSuitor[0]) },
    { "ManPig", kLuxLlamaProfileManPig, sizeof(kLuxLlamaProfileManPig) / sizeof(kLuxLlamaProfileManPig[0]) },
};
static const std::size_t kLuxLlamaProfileCount = sizeof(kLuxLlamaProfiles) / sizeof(kLuxLlamaProfiles[0]);
#endif
