# The Steamworks and standalone GNS headers export identically named interfaces.
# Select exactly one SDK/library for each executable and its static dependencies.
if(NOT EXISTS "${HPL_STEAMWORKS_SDK}/public/steam/steam_api.h")
    message(FATAL_ERROR "Steamworks headers are missing: ${HPL_STEAMWORKS_SDK}")
endif()
get_filename_component(HPL_STEAM_APP_ID_FILE "${CMAKE_CURRENT_LIST_DIR}/../../../steam_appid.txt" ABSOLUTE)
set(HPL_STEAM_APP_ID_FILE "${HPL_STEAM_APP_ID_FILE}" CACHE INTERNAL "Development Steam AppID file")
if(NOT DEFINED HPL_STEAM_APP_ID AND EXISTS "${HPL_STEAM_APP_ID_FILE}")
    file(READ "${HPL_STEAM_APP_ID_FILE}" HPL_STEAM_APP_ID)
    string(STRIP "${HPL_STEAM_APP_ID}" HPL_STEAM_APP_ID)
endif()
set(HPL_STEAM_APP_ID "${HPL_STEAM_APP_ID}" CACHE STRING "Owned Steam AppID compiled into the game")
if(NOT HPL_STEAM_APP_ID MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "Set a numeric HPL_STEAM_APP_ID or supply root steam_appid.txt")
endif()

if(WIN32)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(steam_binary "win64/steam_api64")
    else()
        set(steam_binary "steam_api")
    endif()
    set(steam_runtime "${HPL_STEAMWORKS_SDK}/redistributable_bin/${steam_binary}.dll")
    set(steam_import "${HPL_STEAMWORKS_SDK}/redistributable_bin/${steam_binary}.lib")
elseif(APPLE)
    set(steam_runtime "${HPL_STEAMWORKS_SDK}/redistributable_bin/osx/libsteam_api.dylib")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
    set(steam_runtime "${HPL_STEAMWORKS_SDK}/redistributable_bin/linuxarm64/libsteam_api.so")
elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(steam_runtime "${HPL_STEAMWORKS_SDK}/redistributable_bin/linux64/libsteam_api.so")
else()
    set(steam_runtime "${HPL_STEAMWORKS_SDK}/redistributable_bin/linux32/libsteam_api.so")
endif()
if(NOT EXISTS "${steam_runtime}")
    message(FATAL_ERROR "Steamworks runtime is missing: ${steam_runtime}")
endif()
add_library(HPLSteamworks SHARED IMPORTED GLOBAL)
set_target_properties(HPLSteamworks PROPERTIES
    IMPORTED_LOCATION "${steam_runtime}"
    INTERFACE_INCLUDE_DIRECTORIES "${HPL_STEAMWORKS_SDK}/public"
    INTERFACE_COMPILE_DEFINITIONS "HPL_USE_STEAMWORKS;HPL_STEAM_APP_ID=${HPL_STEAM_APP_ID}")
if(WIN32)
    if(NOT EXISTS "${steam_import}")
        message(FATAL_ERROR "Steamworks import library is missing: ${steam_import}")
    endif()
    set_target_properties(HPLSteamworks PROPERTIES IMPORTED_IMPLIB "${steam_import}")
endif()

function(hpl_deploy_steamworks target)
    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:HPLSteamworks>" "$<TARGET_FILE_DIR:${target}>"
        VERBATIM)
    if(HPL_DEPLOY_STEAM_APP_ID AND EXISTS "${HPL_STEAM_APP_ID_FILE}")
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_if_different "${HPL_STEAM_APP_ID_FILE}" "$<TARGET_FILE_DIR:${target}>/steam_appid.txt"
            VERBATIM)
    endif()
    if(APPLE)
        set_property(TARGET ${target} APPEND PROPERTY BUILD_RPATH "@loader_path")
        set_property(TARGET ${target} APPEND PROPERTY INSTALL_RPATH "@loader_path")
    elseif(UNIX)
        set_property(TARGET ${target} APPEND PROPERTY BUILD_RPATH "$ORIGIN")
        set_property(TARGET ${target} APPEND PROPERTY INSTALL_RPATH "$ORIGIN")
    endif()
endfunction()
